remove useless files  in install_java job to avoid error
Error: Building install_java...
       There are unused template files for job 'install_java': helpers/ctl_setup.sh, helpers/ctl_utils.sh, data/properties.sh.erb, bin/monit_debugger, bin/ctl
       failed